export enum InstructionsType {
  Exchange = 'exchange',
  ExchangeToken = 'exchange_token',
  TradingSymbol = 'trading_symbol',
  GrowwSymbol = 'groww_symbol',
  Name = 'name',
  InstrumentType = 'instrument_type',
  Segment = 'segment',
  Series = 'series',
  Isin = 'isin',
  UnderlyingSymbol = 'underlying_symbol',
  UnderlyingExchangeToken = 'underlying_exchange_token',
  LotSize = 'lot_size',
  ExpiryDate = 'expiry_date',
  StrikePrice = 'strike_price',
  TickSize = 'tick_size',
  FreezeQuantity = 'freeze_quantity',
  IsReserved = 'is_reserved',
  BuyAllowed = 'buy_allowed',
  SellAllowed = 'sell_allowed'
}
